### ISSUE TITLE
orders-service tcp socket rejection during gradle build

### ISSUE THREAD

**Issue by Kirthana14** [eventuate-examples/eventuate-examples-java-customers-and-orders#23]
gradle build of orders-service is giving the tcp socket rejection error.

#  Error

Creating ordersservice_customercommandside_1 ... done
Will use 172.17.0.1 (network bridge) as host of customercommandside
Probing TCP socket on 172.17.0.1:8081 of service 'customercommandside_1'
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))
Waiting for TCP socket on 172.17.0.1:8081 of service 'customercommandside_1' (Connection refused (Connection refused))

**Comment by cer** [comment]
It does take several attempts for the service to startup and accept connections.
However, if it never works then two things to check:

1. Is the docker container customercommandside_1 running? What does `docker ps -a` how? What is the `docker logs` of that container?

2. If there container is running/listening then it could be a networking configuration problem. Please describe your environment; docker version, windows or mac etc? There is code in the Docker plugin - see https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/DockerExecutor.groovy#L111 that is trying to figure out how to access your service?

Also, more generally: what have you set DOCKER_HOST_IP to? Try running https://github.com/eventuate-local-docker-images/eventuateio-docker-networking-diagnostics to verify

**Comment by Kirthana14** [comment]
Actually not all the services are up. Only kafka, zookeeper, mysql, cdc-service, mongodb are up. Remaining services are up for few seconds and then they are down.

# Docker Version:
Docker version 17.12.1-ce, build 7390fc6

#OS:
Ubuntu

#HOST_IP:
I set the DOCKER_HOST_IP with the IP address of the system

#docker ps -a:
70842f71b74f        eventuateexamplesjavacustomersandorders_customercommandside     "/bin/sh -c 'java ${…"   11 minutes ago      Exited (1) 10 minutes ago                                                                              eventuateexamplesjavacustomersandorders_customercommandside_1

When I ran docker ps -a I got the above statement for the service customercommanside with it's previous container id(before it got down).

#docker logs:
## For customercommanside

04:15:09,673 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
04:15:09,674 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
04:15:09,674 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/customers-service.jar!/BOOT-INF/lib/common.jar!/logback.xml]
04:15:09,779 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7699a589 - URL [jar:file:/customers-service.jar!/BOOT-INF/lib/common.jar!/logback.xml] is not of type file
04:15:09,881 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
04:15:09,883 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
04:15:09,904 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
04:15:10,031 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
04:15:10,031 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
04:15:10,031 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
04:15:10,032 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
04:15:10,032 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
04:15:10,040 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.web] to INFO
04:15:10,040 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.web.filter.CommonsRequestLoggingFilter] to DEBUG
04:15:10,040 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
04:15:10,041 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@58372a00 - Registering current configuration as safe fallback point


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

04:15:15.492  ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method eventuateJdbcAccess in io.eventuate.local.java.jdbckafkastore.EventuateLocalConfiguration required a bean of type 'javax.sql.DataSource' that could not be found.
	- Bean method 'dataSource' not loaded because @ConditionalOnProperty (spring.datasource.jndi-name) did not find property 'jndi-name'
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required class 'javax.transaction.TransactionManager'


Action:

Consider revisiting the conditions above or defining a bean of type 'javax.sql.DataSource' in your configuration.

**Comment by cer** [comment]
Thanks for the information

I think the problem is that the build requires has certain requirements for command line options and for environment variables.

Specifically, if you want to build the Eventuate Local version then you need the following:

1.  `./gradlew -P eventuateDriver=local .. `
2.  You also need to set certain environment variables:

* export EVENTUATE_LOCAL=anyValue
* export SPRING_PROFILES_ACTIVE=EventuatePolling|PostgresWal|MySql

The various `build-and-test-all-...sh` script specify these options.

**Comment by Kirthana14** [comment]
Actually the main issue is that all the services are not up.Only kafka, zookeeper, mysql, cdc-service, mongodb are up. Remaining services are up for few seconds and then they are down even after exporting the environment variables.

**Comment by Kirthana14** [comment]
Can the possible reason for service down be the bean datasouce issue?


## Error in customer service using container-id:***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method eventuateJdbcAccess in io.eventuate.local.java.jdbckafkastore.EventuateLocalConfiguration required a bean of type 'javax.sql.DataSource' that could not be found.
	- Bean method 'dataSource' not loaded because @ConditionalOnProperty (spring.datasource.jndi-name) did not find property 'jndi-name'
	- Bean method 'dataSource' not loaded because @ConditionalOnClass did not find required class 'javax.transaction.TransactionManager'

**Comment by cer** [comment]
A few more questions/requests

- Do you have the latest version of the source : git pull?
- have you made any changes locally: git diff ?
- what commands have you run? 
- please send the complete log of the failed service

**Comment by Kirthana14** [comment]
Actually first I wanted to build and run the application using eventuate locale
I ran
**./gradlew assemble -P eventuateDriver=local** 
Build was successful.

**export DOCKER_HOST_IP=Ip address of the system**

**docker-compose -f docker-compose-eventuate-local.yml up -d**
All the 8 services were up and then after few seconds 3 services went down.
 
Then I forcefully attached the container to docker using _docker attach container id_  then it lead to bean datasource error.

**Comment by cer** [comment]
It's possible that the the problem is that the images are not getting rebuild:
Try running one of the following:

* `docker-compose -f docker-compose-eventuate-local.yml build`
* `docker-compose -f docker-compose-eventuate-local.yml up -d --build`

BTW `docker-compose-eventuate-local.yml` isn't present in the very latest version of the project. Its been replaced by `docker-compose-eventuate-local-mysql.yml`

**Comment by Kirthana14** [comment]
docker-compose -f docker-compose-eventuate-local.yml build
Gave Build success.
docker-compose -f docker-compose-eventuate-local.yml up -d --build
Made the services up for few seconds and brought down the customer, order services.

docker-compose-eventuate-local-mysql.yml
Also giving the same issue.

**Comment by Kirthana14** [comment]
ordercommandside_1       | Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
ordercommandside_1       | 	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.start(EventuateKafkaConsumer.java:115)
ordercommandside_1       | 	at io.eventuate.local.java.jdbckafkastore.EventuateKafkaAggregateSubscriptions.subscribe(EventuateKafkaAggregateSubscriptions.java:85)
ordercommandside_1       | 	at io.eventuate.javaclient.commonimpl.EventuateAggregateStoreImpl.subscribe(EventuateAggregateStoreImpl.java:158)
ordercommandside_1       | 	at io.eventuate.javaclient.spring.EventDispatcherInitializer.registerEventHandler(EventDispatcherInitializer.java:105)
ordercommandside_1       | 	at io.eventuate.javaclient.spring.EventHandlerBeanPostProcessor.postProcessBeforeInitialization(EventHandlerBeanPostProcessor.java:25)
ordercommandside_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
ordercommandside_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
ordercommandside_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
ordercommandside_1       | 	... 23 common frames omitted
ordercommandside_1       | Caused by: java.lang.RuntimeException: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
ordercommandside_1       | 	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.verifyTopicExistsBeforeSubscribing(EventuateKafkaConsumer.java:48)
ordercommandside_1       | 	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.start(EventuateKafkaConsumer.java:70)
ordercommandside_1       | 	... 30 common frames omitted
ordercommandside_1       | **Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
eventuateexamplesjavacustomersandorders_ordercommandside_1 exited with code 1**

**Comment by cer** [comment]
Well that is promising. Looks like the image is built correctly. Now you have a networking problem - see #24
