### ISSUE TITLE
Bean initialization issue in customer service

### ISSUE THREAD

**Issue by Kirthana14** [eventuate-examples/eventuate-examples-java-customers-and-orders#24]
After gradle build is successful. During the jar execution leads to bean initialization isuue.

# Error
11:40:23.227  ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customerWorkflow' defined in class path resource [net/chrisrichardson/eventstore/examples/customersandorders/customersservice/backend/CustomerBackendConfiguration.class]: Initialization of bean failed; nested exception is io.eventuate.EventuateSubscriptionFailedException: Subscription failed: customerWorkflow
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at net.chrisrichardson.eventstore.examples.customersandorders.customersservice.CustomersServiceMain.main(CustomersServiceMain.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: io.eventuate.EventuateSubscriptionFailedException: Subscription failed: customerWorkflow
	at io.eventuate.javaclient.spring.EventDispatcherInitializer.registerEventHandler(EventDispatcherInitializer.java:109)
	at io.eventuate.javaclient.spring.EventHandlerBeanPostProcessor.postProcessBeforeInitialization(EventHandlerBeanPostProcessor.java:25)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 23 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.eventuate.javaclient.spring.EventDispatcherInitializer.registerEventHandler(EventDispatcherInitializer.java:106)
	... 27 common frames omitted

**Comment by cer** [comment]
Presumably this failure is responsible for #23

**Comment by cer** [comment]
This indicates that the service cannot connect to Kafka. What have you set DOCKER_HOST_IP to? The most likely explanation is that it is incorrect. What environment are you running Windows/Mac?

Try running https://github.com/eventuate-local-docker-images/eventuateio-docker-networking-diagnostics to verify

**Comment by Kirthana14** [comment]
When I ran the above application I got 504 status.
$:/node app.js
DOCKER_HOST_IP= iP of system
Server running on port: 8889
About to make HTTP request to self
Making HTTP request to self via url= http://IP of system:8889
FAILURE:  null
response.statusCode= 504

**Comment by cer** [comment]
Two things:

1. 504 is a Gateway timeout - is your machine configured to use a proxy?
2. The intended way to run eventuateio-docker-networking-diagnostics is to git clone and docker-compose up 
3. How did you determine the IP address of your machine?

**Comment by Kirthana14** [comment]
I got the IP address(IPv4) of machine from network folder.

**Comment by Kirthana14** [comment]
docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting eventuateiodockernetworkingdiagnostics_diagnostics_1 ... done
Attaching to eventuateiodockernetworkingdiagnostics_diagnostics_1
**diagnostics_1  | DOCKER_HOST_IP= 10.138.77.31
diagnostics_1  | Server running on port: 8888
diagnostics_1  | About to make HTTP request to self
diagnostics_1  | Making HTTP request to self via url= http://10.138.77.31:8888
diagnostics_1  | SUCCESSS!!!!**
_eventuateiodockernetworkingdiagnostics_diagnostics_1 exited with code 0_
